DROP TABLE IF EXISTS ADMINISTRATOR;

CREATE TABLE ADMINISTRATOR (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50),
	password VARCHAR(400) NOT NULL,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,	
	email VARCHAR(30) NOT NULL
	
);