DROP TABLE IF EXISTS SMASHCHARACTER;
DROP TABLE IF EXISTS ADMINISTRATOR;

CREATE TABLE ADMINISTRATOR (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(400) NOT NULL,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,	
	email VARCHAR(30) NOT NULL
	
);

CREATE TABLE SMASHCHARACTER (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
	description VARCHAR(500) NOT NULL,
	weight INT NOT NULL,
	gravity VARCHAR(20) NOT NULL,
	render VARCHAR(500) NOT NULL,
	adminId BIGINT NOT NULL,
	CONSTRAINT AdminIdFK FOREIGN KEY(adminId)
	REFERENCES Administrator(id)
);