DROP TABLE IF EXISTS ADMIN;

CREATE TABLE ADMIN (
	username VARCHAR(50) PRIMARY KEY,
	email VARCHAR(30) NOT NULL,
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL
);